spring.application.name=order-hub
server.port=8081

spring.cloud.aws.region.static=ap-southeast-2
spring.cloud.aws.credentials.type=default

aws.dynamodb.table-name=order-hub-orders
aws.sqs.dispatch-queue=https://sqs.ap-southeast-2.amazonaws.com/984454382434/dispatch-orders

springdoc.swagger-ui.path=/swagger-ui.html

resilience4j.circuitbreaker.instances.driverApi.slidingWindowSize=10
resilience4j.circuitbreaker.instances.driverApi.failureRateThreshold=50
resilience4j.circuitbreaker.instances.driverApi.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.driverApi.permittedNumberOfCallsInHalfOpenState=3

resilience4j.retry.instances.driverApi.maxAttempts=3
resilience4j.retry.instances.driverApi.waitDuration=1s
resilience4j.retry.instances.driverApi.enableExponentialBackoff=true
resilience4j.retry.instances.driverApi.exponentialBackoffMultiplier=2
